### PR TITLE
Update subdomains.json, with name eesa

### PR DESCRIPTION
**Pull request by eesazahed**
added my first name (eesa) to the list

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
site is up and can be accessed. a portfolio site.

image

**Comment by lakuapik** [comment]
@eesazahed thedev.id team already created a CNAME for your site. 

what you need to do next is add `eesa.thedev.id` to your github page custom domain.

example:

image

**Comment by lakuapik** [comment]
@eesazahed any update on this? have you try it?

**Comment by eesazahed** [comment]
Actually, after consideration, I do not not want this subdomain. Thanks anyway.

**Pull request closed without merging**
