### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by xBLOCK-HEADx**
add blockhead

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a blog website: 

image

**Comment by lakuapik** [comment]
@xBLOCK-HEADx thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image


what you need to do next is add `blockhead.thedev.id` to your github page custom domain.

example:

image

**Comment by xBLOCK-HEADx** [comment]
Thanks, the custom domain needs verification:

1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-xBLOCK-HEADx.blockhead.thedev.id
2. Use this code for the value of the TXT record: 69b37c56bc5bca4aa1e02125cbdff5
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.

**Comment by lakuapik** [comment]
@xBLOCK-HEADx its not thedev.io, but thedev.id.

**Comment by xBLOCK-HEADx** [comment]
oops! sorry about that, all seems to be OK now :)

**Comment by lakuapik** [comment]
@xBLOCK-HEADx great! the site now can be accessed with thedev.id domain:

image

**Pull request merged**
