### PR TITLE
Add darvzac

### PR DESCRIPTION
**Pull request by darvzac**

### CODE REVIEW

**Comment by lakuapik** [comment]
@darvzac please make sure your site is up and can be accessed so thedev.id team can verify it. 

feel free to reopen necessary.

**Comment by darvzac** [comment]
The site is online now

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a personal profile website.

image

--- 

@darvzac gpp kalau mau pake bahasa indonesia. sama ini tolong diurutin ya, jangan tambah di paling bawah, urutkan sesuai abjad.

**Comment by lakuapik** [comment]
@darvzac thedev.id team already created a CNAME for your site `darvzac.thedev.id` 🎉

But unfornately, there is an SSL issue on your site.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `darvzac.thedev.id`.

**Comment by darvzac** [comment]
Keknya gw mau ganti hostingan aja deh hostingan yang gw pake buat nih website aneh buat domainnya ditulis disitu belum kebaca domainnya

**Comment by lakuapik** [comment]
@darvzac ada update untuk ini?

**Comment by lakuapik** [comment]
@darvzac seperitnya kamu sudah melakukan update.

the site is now up and can be accessed using thedev.id subdomain:

image

**Pull request merged**
