### PR TITLE
requested adarsh.thedev.id

### PR DESCRIPTION
**Pull request by adarssh01**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up and accessible, its a portfolio website:

image

**Comment by lakuapik** [comment]
@adarssh01 i've added the cname for your site. what you need to do next to make your site accessible is: configure your domain in your azure custom domain settings.

image


let me know if you've made a change.

**Comment by adarssh01** [comment]
Hello David,
I have configured the domain in the Azure custom domain settings.
Please let me know what to do next.
thanks

**Comment by lakuapik** [comment]
@adarssh01 that's all. now your site is accessible with thedev.id domain.

image

i will merge this PR.

**Comment by lakuapik** [comment]
@adarssh01 can you reorder the subdomain.json file? i will after that.

**Pull request merged**
