### PR TITLE
add subdomain 'dook'

### PR DESCRIPTION
**Pull request by floooptimism**

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
the site is up, can be accessed, is a portfolio website.

image

**Comment by lakuapik** [comment]
@floooptimism thedev.id team already created a CNAME for your site 🎉

But unfornately, there is an SSL issue on your site.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `dook.thedev.id`.

Please refer to [this vercel documentation](https://docs.netlify.com/domains-https/custom-domains/) and [also this one](https://vercel.com/docs/concepts/projects/domains).

**Comment by floooptimism** [comment]
Added the custom domain pointing to `dook.thedev.id`. It's working now. 
Thanks!

**Comment by lakuapik** [comment]
site is up using thedev.id subdomain 🚀 

image

**Pull request merged**
