### PR TITLE
[Add] miti99 subdomain

### PR DESCRIPTION
**Pull request by tiennm99**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@tiennm99 thedev.id team has created a cname for your site 🎉

but unfornately, just like #444, there is a cname issue caused by invalid configuration:

image

what you need to do is, go to your cloudflare pages custom domain settings and add `miti99.thedev.id`.

**Comment by tiennm99** [comment]
I configured it. Thank you!
image

**Comment by lakuapik** [comment]
@tiennm99 great!

now the site is up using thedev.id domain:

image

**Comment by tiennm99** [comment]
Thank you! @lakuapik

**Pull request merged**
