### PR TITLE
add subdomain "paban"

### PR DESCRIPTION
**Pull request by Pabanjyoti**
Requested Subdomain:
paban

My site:
https://pabanjyoti.github.io/

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@Pabanjyoti thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `paban.thedev.id` to your github page custom domain and dont forget to check enforece https.

example:

image

**Comment by Pabanjyoti** [comment]
Thank You, I have updated the custom domain. Now the site is accessible from https://paban.thedev.id/ and original GitHub link also redirects to the same.

**Comment by Pabanjyoti** [comment]
Thank You, I have updated the custom domain. Now the site is accessible from https://paban.thedev.id/ and original GitHub link also redirects to the same.

**Comment by lakuapik** [comment]
i will merge this PR

**Comment by lakuapik** [comment]
the site now can be accessed with thedev.id domain:

image

**Pull request merged**
