### PR TITLE
(Again)Update subdomains.json - Added tawhid.thedev.id

### PR DESCRIPTION
**Pull request by Dumbo-programmer**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up and accessible, its a portfolio website:

image

**Comment by lakuapik** [comment]
@Dumbo-programmer thedev.id team has created a cname for your site:

image

what you need to do next is go to your repl custom domain settings and add `tawhid.thedev.id` and turn on https.

let me know if you have configure it.

**Comment by Dumbo-programmer** [comment]
oh my bad, replit suggests `880ad1fe-1090-4dcc-976a-24b5bc2a0b5d.id.repl.co` for the canonical name

**Comment by Dumbo-programmer** [comment]
Cloudfare verification txt: `replit-verify=880ad1fe-1090-4dcc-976a-24b5bc2a0b5d`

**Comment by lakuapik** [comment]
@Dumbo-programmer i've updated the cname 

image

**Comment by Dumbo-programmer** [comment]
Thank you! It's working now <3

**Comment by lakuapik** [comment]
great!

image

now i will merge this PR.

**Pull request merged**
