### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by gamersindo1223**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site can is accessible, its a personal portfolio website:

image

---

@gamersindo1223 please put your domain in subdomains.json file sorted alphabetically.

**Comment by lakuapik** [comment]
@gamersindo1223 thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `gamersindo.thedev.id` to your github page custom domain.

example:

image

**Comment by gamersindo1223** [comment]
@lakuapik fixed!!
now do you know how to add multiple domains on github pages?

**Comment by lakuapik** [comment]
@gamersindo1223 great! now your site is accessible with thdev.id domain:

image

**Pull request merged**
