### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by gamersindo1223**

### CODE REVIEW

**Comment by lakuapik** [comment]
@gamersindo1223 what about the last one? can you explain why you need to change the current domain?

**Comment by gamersindo1223** [comment]
changed from github pages to cloudflared, bcuz github pages only support 1 doamins
i want to register it here and .is-an.dev domain

**Comment by lakuapik** [comment]
the site is accessible, its a portfolio website:

image

**Comment by lakuapik** [comment]
@gamersindo1223 i've just changed your cname to the new domain. please configure your custom domain in your cloudflare pages settings. let me know if you've made a change so i can merge this PR. thanks.

**Comment by gamersindo1223** [comment]
accessable!
closing

**Comment by lakuapik** [comment]
great!

**Pull request merged**
