### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by WistfulShenanigans**
This is my personal site.
So far, I have only completed the home page. However, I am currently working on the blog and projects page.
I hope to obtain the domain `wist.thedev.id`.
Here is a preview of my personal site (without the background image):
image
Thank you for reviewing my subdomain request!

### CODE REVIEW

**Comment by lakuapik** [comment]
@WistfulShenanigans fair enough, i will proceed the verification process.

**Comment by lakuapik** [comment]
the site up and accessible, its a personal website:

image

**Comment by lakuapik** [comment]
@WistfulShenanigans thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

what you need to do next is add `wist.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by WistfulShenanigans** [comment]
Okay, I have done so.

**Comment by WistfulShenanigans** [comment]
image

**Comment by WistfulShenanigans** [comment]
image
The site is now up and running. Thank you! I will close this pull request now.

**Pull request merged**
