### PR TITLE
debug.thedev.id

### PR DESCRIPTION
**Pull request by Satindar31**
I added a website for myself (debug)

### CODE REVIEW

**Comment by Satindar31** [comment]
bump

**Comment by fransallen** [comment]
@Satindar31 maybe use unique name like `satindar` or `satindar31` instead of common name like `debug`?

**Comment by lakuapik** [comment]
@Satindar31 thedev.id does not allow the use of generic domain like `debug`, as frans suggested, you could use `satindar` or `satindar31`. If you want the subdomain i can help rebase the PR and merge after it.

**Comment by lakuapik** [comment]
@Satindar31  i will mark this invalid for the moment, if you still want the domain, just reopen this PR, thanks.

**Pull request closed without merging**
