### PR TITLE
Add william.thedev.id

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**
The domain will redirect to https://williamharrison.dev

### CODE REVIEW

**Review by lakuapik — CHANGES_REQUESTED** [review]
@WilliamDavidHarrison, what do you mean by the redirect? 

right now, here is the site when i visit your domain:

image

also, fyi we dont allow thedev.id subdomain to be used as a redirect domain.

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison, what do you mean by the redirect?
> 
> right now, here is the site when i visit your domain:
> 
> image
> 
> also, fyi we dont allow thedev.id subdomain to be used as a redirect domain.

I'll use it to host my dev website: https://github.com/williamdavidharrison/dev-website

`dns.williamharrison.xyz` is a reverse proxy, that's why there is a login page.

**Comment by lakuapik** [comment]
@WilliamDavidHarrison for verification, the site need to be up and running so i can screenshot it.

**Comment by lakuapik** [comment]
@WilliamDavidHarrison or can you setup first the domain `william.thedev.id` in your reverse proxy? so i can check it right away after adding the cname.

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison for verification, the site need to be up and running so i can screenshot it.

It is on https://williamharrison.dev atm

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison or can you setup first the domain `william.thedev.id` in your reverse proxy? so i can check it right away after adding the cname.

I've set it up

**Comment by lakuapik** [comment]
@WilliamDavidHarrison i've added the cname, please check on you side.

image

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison i've added the cname, please check on you side.
> 
> image

I fixed it.

**Comment by lakuapik** [comment]
@WilliamDavidHarrison as i said earlier, we dont allow thedev.id subdomain to be used as a redirect to another website. 

We will allow it if you host a website directly under `william.thedev.id`.

Just like me, i have https://davids.id and also https://david.thedev.id running at the same time.

What do you think? would you still use thedev.id subdomain?

**Pull request closed without merging**
