### PR TITLE
Add saksham.thedev.id

### PR DESCRIPTION
**Pull request by OshekharO**
Hello, creating a subdomain for my portfolio site. Thank you!

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up and accessible, its a personal website:

image

**Comment by lakuapik** [comment]
@OshekharO thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

what you need to do next is add `saksham.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by OshekharO** [comment]
@lakuapik Custom domain added and HTTPS Enforced. Thanks!

**Comment by lakuapik** [comment]
@OshekharO great! your site is now acessible with thedev.id domain:

image

**Pull request merged**
