### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by Elijah629**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up and accessible:

image

its a portfolio website.

**Comment by lakuapik** [comment]
@Elijah629  thedev.id team has created a cname for your site  🎉

image

But unfornately, there is an SSL issue.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `https://elijah629.thedev.id`.

Please refer to [this vercel documentation](https://vercel.com/docs/concepts/projects/domains/add-a-domain).

**Comment by Elijah629** [comment]
Done! Thank you!

**Comment by lakuapik** [comment]
site is accessible with thedev.id subdomain:

image

**Pull request merged**
