### PR TITLE
Update subdomains

### PR DESCRIPTION
**Pull request by fitrahfm**
Added {"fitrahfm": "fitrahfm.vercel.app"} in subdomains.js

### CODE REVIEW

**Comment by lakuapik** [comment]
@fitrahfm  unfornately, your site does not meet our requirements.

image

your site must be in one of these criteria:
- a personal website
- a portfolio website
- a blog website
- a project (landing/documentation) website

and has enough content for verification. not just a starter template/boilerplate.

**Comment by fitrahfm** [comment]
Thank you for the info. I am planning to using this sub-domain for my portfolio.

**Comment by fitrahfm** [comment]
> @fitrahfm unfornately, your site does not meet our requirements.
> 
> image
> 
> your site must be in one of these criteria:
> 
> * a personal website
> * a portfolio website
> * a blog website
> * a project (landing/documentation) website
> 
> and has enough content for verification. not just a starter template/boilerplate.

Thank you for the info. I am planning to using this sub-domain for my portfolio.

**Comment by fitrahfm** [comment]
Hi, @lakuapik, I just created my web profile.

You can check my web here: https://fitrahmunir.vercel.app

**Comment by fitrahfm** [comment]
> Hi, @lakuapik, I just created my web profile.
> 
> You can check my web here: https://fitrahmunir.vercel.app

I am migrating my host to cloudflare, because sometimes i got an SSL error if using vercel

**Pull request closed without merging**
