### PR TITLE
"mateen" added to subdomain.json

### PR DESCRIPTION
**Pull request by mateenozil**

### CODE REVIEW

**Comment by mateenozil** [comment]
Thanks, guys.

**Comment by lakuapik** [comment]
@mateenozil thedev.id team already add CNAME for the subdomain. 

What you need to do next is make sure your site use HTTPS and make sure the custom domain pointed to `mateen.thedev.id`.

Please refer to [this netflify documentation](https://docs.netlify.com/domains-https/custom-domains/).

**Comment by mateenozil** [comment]
Hi,

Just close it. I have a new domain.

Sorry for the inconvenience.

Regards,
Mateen

**Comment by lakuapik** [comment]
@mateenozil its okay, me as one of thedev.id team also want to say sorry for slow response.

either way, have a nice day!

**Pull request closed without merging**
