### PR TITLE
Adds my domain to the list

### PR DESCRIPTION
**Pull request by philphirn**
I frequently test my code on Google Cloud, using a short domain name instead of copy pasting the longer one every time will be of a great help to me.

Thank you in advance.

Cheers,
Phillip.

### CODE REVIEW

**Review by lakuapik — CHANGES_REQUESTED** [review]
@philphirn i just check your site and its not found. 

image

Please make sure the site is up so we can verify it.

**Comment by philphirn** [comment]
Hi 👋 @lakuapik,

Ohh I forgot to inform you that does not operate on the plain HTTP protocol. It's something like We bsockets. Also I use it for testing and it's not up every time (as I incur charges on my Google Cloud). So I just made this PR to get a shorter domain name so that I don't have to type so long everytime. Also I've kept the name a little random so that others don't have problems.

If you find any objectionable behaviour, then feel free to remove the domain name anytime without even informing me (but I promise as a developer you won't).

Now leaving it upon you.

Thanks in advance.
Cheers,
Phillip.

**Comment by fransallen** [comment]
@philphirn I'd recommend that you use thedev.id subdomain for accessible website like personal site, portfolio, or project's landing page.

In the current state I believe those are the most suitable use cases for this project.

**Comment by philphirn** [comment]
> @philphirn I'd recommend that you use thedev.id subdomain for accessible website like personal site, portfolio, or project's landing page.
> 
> In the current state I believe those are the most suitable use cases for this project.

Hey @fransallen, but I don't understand, what's the problem in accepting my submission ?

**Comment by lakuapik** [comment]
@philphirn the site still cant be accessed for verification. 

as @fransallen said, thedev.id domain is suitable for project like personal site, portolio or project landing page. 

so i will mark this as `invalid` and close this PR.

 feel free to re-open or re-PR if you've made a change. thanks!

**Pull request closed without merging**
