### PR TITLE
add new subdomains

### PR DESCRIPTION
**Pull request by bryantobing12**
this is my personal website. 

Thanks

### CODE REVIEW

**Comment by lakuapik** [comment]
@bryantobing12 thedev.id team already created a CNAME for your site 🎉

But unfornately, there is a not found issue, which is caused by invalid configuration.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `bryan.thedev.id`.

Please refer to [this vercel documentation](https://vercel.com/docs/concepts/projects/domains/add-a-domain).

**Comment by lakuapik** [comment]
@bryantobing12 any update on this?

**Comment by bryantobing12** [comment]
Hi. Sorry for the delay..will check on this as soon as i have time.

**Comment by lakuapik** [comment]
@bryantobing12 let me know if you've made an update, i will merge this PR after it.

**Comment by bryantobing12** [comment]
I have configured the domain. Thanks for the help @lakuapik

**Comment by lakuapik** [comment]
@bryantobing12 great!

now the site can be accessed with thedev.id domain:

image

**Pull request merged**
