### PR TITLE
Added darkshark.thedev.id

### PR DESCRIPTION
**Pull request by benjaminwolkchen**

### CODE REVIEW

**Comment by lakuapik** [comment]
@benjaminwolkchen we can access your site. please wait our team to process it. 

image

**Comment by Arezoomohammadalizadeh** [comment]
thankyou

**Comment by lakuapik** [comment]
@benjaminwolkchen unfornately, right now its impossible to add CNAME to cloudflare pages, its because cloudflare did not allow cross-account-cname, you can [read more here](https://community.cloudflare.com/t/why-cname-cross-user-banned/237595/8). just like https://github.com/thedev-id/thedev.id/pull/444.

---

if you still want the domain, maybe consider moving the website to github pages / vercel / netlify. thanks.

**Comment by lakuapik** [comment]
@benjaminwolkchen turns out it is possible to cross-user-cname cloudflare. we just need to configure it.

thedev.id team has created a cname for your site 🎉

image

what you need to do next is, go to your cloudflare pages settings, make sure to point the custom domain to `darkshark.thedev.id`

example:

image

**Comment by lakuapik** [comment]
@benjaminwolkchen looks like you've configured it.

the site now can be accessed with thedev.id domain:

image

**Pull request merged**
