### PR TITLE
Add Me

### PR DESCRIPTION
**Pull request by Spz2022**

### CODE REVIEW

**Comment by lakuapik** [comment]
@Spz2022 thdev.id team has created a CNAME for your site

but unfornately, it has an SSL issue:

image


please check again the settings for your github pages and make sure you check the enforce https.

**Comment by Spz2022** [comment]
I don't want to open https because this site is for old phones

**Comment by lakuapik** [comment]
@Spz2022 what do you mean by old phones?

**Comment by lakuapik** [comment]
@Spz2022 thedev.id enforce all subdomain to activate https. its your choice to not activate https, but it will resulting the site cannot be accessed. so do you still want the domain or not? if yes just activate the https, if not i will remove the cname. thanks.

**Comment by Spz2022** [comment]
ok yes

**Comment by Spz2022** [comment]
Unavailable for your site because a
certificate has not yet been issued for your domain

**Comment by Spz2022** [comment]
ok

**Comment by lakuapik** [comment]
@Spz2022 i've just check your site again, unfornately the content did not meet our requirements. 

at least it should be:
- a portfolio website
- a blog website
- a project website

and the content must be enough for verification. 

right now your site is just a `hello world` site. 

image

with that said, i will remove your cname for now and close this PR.

feel free to re-open or re-PR if you've made a change. thanks!

**Pull request closed without merging**
