### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by RojanGamingYT**

### CODE REVIEW

**Comment by RojanGamingYT** [comment]
done

**Comment by lakuapik** [comment]
@RojanGamingYT thedev.id team already created a cname for your site.

but unfornately, it is not accessable yet because of invalid configuration:

image

please make sure you check `Enforce HTTPS` in your github page custom domain settings.

--

after you've configured it, i will continue the verifcation and merge this PR.

**Comment by RojanGamingYT** [comment]
fixed

**Comment by lakuapik** [comment]
@RojanGamingYT great!

now the site is acessible with thedev.id domain, its a portfolio website:

image

**Pull request merged**
