### PR TITLE
Pranshu05

### PR DESCRIPTION
**Pull request by pranshu05**

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
image

**Comment by lakuapik** [comment]
@pranshu05 thedev.id team already created a CNAME for your site. 

what you need to do next is to add `pranshu05.thedev.id` to your github page custom domain.

go to https://github.com/pranshu05/pranshu05.github.io/settings/pages

example:

image

**Comment by pranshu05** [comment]
Yea I did it... Thanks!

**Comment by lakuapik** [comment]
site is up with thedev.id domain

image

**Pull request merged**
