### PR TITLE
codewhiteweb.thedev.id

### PR DESCRIPTION
**Pull request by CodeWhiteWeb**

### CODE REVIEW

**Comment by lakuapik** [comment]
@CodeWhiteWeb sorry for late response!

i've just check your site https://codewhiteweb.github.io and now its using domain `codewhiteweb.cf`.

do you still want to use thedev.id subdomain? if yes, i will help you set it up, if not, we can close this PR and move on. thanks.

**Comment by CodeWhiteWeb** [comment]
Yes please set it up as after few weeks my free plan of subdomain will expire

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@CodeWhiteWeb thedev.id team has created a CNAME for your site 🎉

image

what you need to do next is add `codewhiteweb.thedev.id` to your github page custom domain.

example: 

image

**Comment by CodeWhiteWeb** [comment]
done!
What next?

**Comment by lakuapik** [comment]
@CodeWhiteWeb thats it! 

if you want to have HTTPS, make sure you check `Enforce HTTPS` in the github custom domain setting.

---

anyway, the site is up using thedev.id subdomain 🚀

image

**Pull request merged**
