### PR TITLE
Added carter domain and sorted

### PR DESCRIPTION
**Pull request by neopunisher**
Thanks!

### CODE REVIEW

**Review by lakuapik — CHANGES_REQUESTED** [review]
even though the site is up and can be accessed, the content does not meet the criteria.

image

please make sure your site meet one of these criteria:
* is a personal website
* is a portfolio website
* is a project showcase website

and have enough content so thedev.id can verify it.

**Comment by neopunisher** [comment]
Ok i added the assets and first blog post. I plan to continue to add to the content and functionality

**Comment by neopunisher** [comment]
here is a new preview 
image

**Review by lakuapik — APPROVED** [review]
@neopunisher great!

the site is up, can be accessed, is a portfolio website.

image

**Comment by lakuapik** [comment]
@neopunisher thedev.id team already created a CNAME for your site 🎉

image

what you need to do next is to add `carter.thedev.id` to your github page custom domain.

example: 

image

**Comment by neopunisher** [comment]
done thank you! custom domain setup 
image

Anything else I need to do?

**Comment by lakuapik** [comment]
@neopunisher thats all! i will merge this PR right away.

**Pull request merged**
