### PR TITLE
Added amaanwarsi

### PR DESCRIPTION
**Pull request by amaanwarsi**

### CODE REVIEW

**Comment by fransallen** [comment]
Thank you!

**Comment by lakuapik** [comment]
@amaanwarsi thedev.id team already create a CNAME for your subdomain. 

Right now, what you need to do is solve the SSL issue:

image

For github page, go to the [repository settings](https://github.com/amaanwarsi/amaanwarsi.github.io/settings/pages) and make sure its pointed to `amaanwarsi.thedev.id`. Example below:

image

**Comment by lakuapik** [comment]
@amaanwarsi any update? if not i will close this one within 24 hours.

**Comment by lakuapik** [comment]
@amaanwarsi i will mark this as canceled, if you still want the domain, plase make new PR. thanks!

**Pull request closed without merging**
