### PR TITLE
Mrpreet.dev

### PR DESCRIPTION
**Pull request by jsonpreet**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio developer:

image

**Comment by lakuapik** [comment]
@jsonpreet thedev.id team already created a CNAME for your site  🎉

But unfornately, there is an SSL issue on your site.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `mrpreet.thedev.id`.

**Comment by lakuapik** [comment]
@jsonpreet any update for this?

**Comment by jsonpreet** [comment]
Hy sorry i noticed that, let me check and solve issue thank you 🙏

**Comment by lakuapik** [comment]
@jsonpreet let me know if you've configured it so i can merge this PR, thanks.

**Comment by jsonpreet** [comment]
Hi, I fixed that, Please merge it.

Thanks.

**Comment by lakuapik** [comment]
@jsonpreet the ssl issue still exists

image

**Comment by lakuapik** [comment]
@jsonpreet and because [you try to change the entry from the original request](
https://github.com/thedev-id/thedev.id/pull/437/commits/efd1c9b8ae076ccf31b2730e99949dbdd505c8ea) i will remove the cname and mark this as invalid.

**Pull request closed without merging**
