### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by QwertyIsCoding**
:)

### CODE REVIEW

**Comment by fransallen** [comment]
Thank for the PR @QwertyIsCoding, do you still need the subdomain?

**Comment by QwertyIsCoding** [comment]
I mean... I guess? I am not too sure what you mean by that... I just thought that the subdomain looked cool and would be great to redirect to my main site...

**Comment by fransallen** [comment]
> would be great to redirect to my main site

I would recommend using thedev.id subdomain as the primary address of the personal site and not just a redirect, so that the project can be useful. If you want to use thedev.id subdomain as your personal site address, again, not just a redirect, I'd be happy to merge this PR.

**Comment by lakuapik** [comment]
@QwertyIsCoding i believe you already use the `https://qwerty.is-a.dev/`.

And as i've check just now, the github.io domain is not found.

image

@fransallen i will close this one. 

@QwertyIsCoding if you still want the domain, please re PR. Thank you.

**Pull request closed without merging**
