### PR TITLE
add william.thedev.id

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
You'll need to add the record to the zone file first to set-up https.

**Comment by lakuapik** [comment]
@WilliamDavidHarrison will this still a redirect or not?

https://github.com/thedev-id/thedev.id/pull/506

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison will this still a redirect or not?
> 
> https://github.com/thedev-id/thedev.id/pull/506

No, I'm putting a code server on it

**Comment by lakuapik** [comment]
@WilliamDavidHarrison i've added the CNAME, please check on your side.

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison i've added the CNAME, please check on your side.

I've generated an SSL. It should work now.

**Comment by lakuapik** [comment]
Is this what it supposed to be displayed? a code server? not a personal/portfolio/project/blog website?

image

**Comment by WilliamDavidHarrison** [comment]
> Is this what it supposed to be displayed? a code server? not a personal/portfolio/project/blog website?
> 
> image
> 

Yes. It's Visual Studio Code on the web.

**Comment by lakuapik** [comment]
i see. unfornately, a personal tool is not allowed to have thedev.id domain. our requirements is: the site must be in one of these types:

- a personal website
- a portfolio website
- a blog website
- a project website

and must be public with enough content for verification.

@WilliamDavidHarrison do you have a plan to switch the domain with new website? if not i will remove the cname and close this PR.

**Comment by WilliamDavidHarrison** [comment]
> i see. unfornately, a personal tool is not allowed to have thedev.id domain. our requirements is: the site must be in one of these types:
> 
> - a personal website
> - a portfolio website
> - a blog website
> - a project website
> 
> and must be public with enough content for verification.
> 
> @WilliamDavidHarrison do you have a plan to switch the domain with new website? if not i will remove the cname and close this PR.

If you wanted I could copy my current dev website and put it on there: https://wdh.gg/dev

**Comment by lakuapik** [comment]
@WilliamDavidHarrison its up to you. as long as the requested domain has content that meet our requirements.

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison its up to you. as long as the requested domain has content that meet our requirements.

Done

**Comment by lakuapik** [comment]
the site is now accessible with thedev.id domain:

image

**Pull request merged**
