### PR TITLE
Update youngchief.thedev.id

### PR DESCRIPTION
**Pull request by youngchief-btw**

### CODE REVIEW

**Comment by lakuapik** [comment]
@youngchief-btw please make sure your site can be accessed so we can verify it. 

image

**Comment by Arezoomohammadalizadeh** [comment]
thankyou

**Comment by Arezoomohammadalizadeh** [comment]
A thankyou

**Comment by youngchief-btw** [comment]
Haha! Sorry, I haven't been checking my GitHub notifications. I'll fix the site soon. The issue appears to be a config issue.

**Pull request merged**
