### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by its-rainy-days**

### CODE REVIEW

**Comment by lakuapik** [comment]
@its-rainy-days thedev.id team already created a cname for your site.

but unfornately, it is not accessable yet because of invalid configuration:

image


please make sure you check `Enforce HTTPS` in your github page custom domain settings.

**Comment by its-rainy-days** [comment]
@lakuapik I can't check "Enforce HTTPS" in my github page.
image

**Comment by its-rainy-days** [comment]
@lakuapik I've already resolved the problem. I've check "Enforce HTTPS".

**Comment by lakuapik** [comment]
the site is now accessable with thedev.id, its a personal site:

image

**Pull request merged**
