### PR TITLE
update bro

### PR DESCRIPTION
**Pull request by Notdet3cted**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@Notdet3cted thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `npl.thedev.id` to your github page custom domain.

example:

image

**Comment by Notdet3cted** [comment]
thanks bro, your reply very helpfull ❤️

**Comment by lakuapik** [comment]
@Notdet3cted great!

the site now can be accessed with thedev.id domain:

image

**Pull request merged**
