### PR TITLE
Add jay to subdomains.json

### PR DESCRIPTION
**Pull request by lonewanderer27**

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
site is up and can be accessed, it is a portfolio website.

image

**Comment by lakuapik** [comment]
@lonewanderer27 thedev.id team already created a CNAME for your site. 

image

what you need to do next is add `jay.thedev.id` to your github page custom domain.

go to https://github.com/lonewanderer27/lonewanderer27.github.io/settings/pages

example:

image

**Comment by lonewanderer27** [comment]
Cool! Thank you very much for this subdomain 😊

**Comment by lakuapik** [comment]
@lonewanderer27 can you resolve the conflict for me? i will merge after this. thanks.

**Comment by lakuapik** [comment]
site is up and running with thedev.id subdomain:

image

**Pull request merged**
