### PR TITLE
[Add] deviltux.thedev.id subdomain

### PR DESCRIPTION
**Pull request by duraki**
Added a new CNAME entry via `deviltux` alias, pointing to my [blog](https://duraki.github.io)

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a blog website:

**Comment by lakuapik** [comment]
@duraki thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `deviltux.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by duraki** [comment]
Absolutely, my pleasure. Just added custom domain w/ enforced HTTPS. Thanks @lakuapik ☘️

**Comment by lakuapik** [comment]
@duraki awesome! the site now can be accessed with thedev.id domain:

image

i will merge this PR.

**Pull request merged**
