### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by ArijitTheDev**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a profile website:

image

**Comment by lakuapik** [comment]
@ArijitTheDev thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image


what you need to do next is add `arijit.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by lakuapik** [comment]
@ArijitTheDev any update on this?

**Comment by lakuapik** [comment]
there is no update from @ArijitTheDev so i will mark this as invalid-no-response and remove the cname. feel free to re-request by opening this PR or creating a new one. thanks.

**Comment by ArijitTheDev** [comment]
> there is no update from @ArijitTheDev so i will mark this as invalid-no-response and remove the cname. feel free to re-request by opening this PR or creating a new one. thanks.

Hello I was offline, can you reopen the cname

**Comment by lakuapik** [comment]
@ArijitTheDev i've re-add the cname.

**Comment by ArijitTheDev** [comment]
> @ArijitTheDev i've re-add the cname.

The custom domain DNS check is unsuccessful

**Comment by ArijitTheDev** [comment]
Ok its successful now! Site working

**Comment by lakuapik** [comment]
@ArijitTheDev great! now your site is accessible with thedev.id domain:

image

**Pull request merged**
