### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by DanyTPG**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a blog website:

image

**Comment by lakuapik** [comment]
@DanyTPG thedev.id team already created a CNAME for your site 🎉

But unfornately, cloudflare policy does not allow a cross-user CNAME:

image

**Comment by DanyTPG** [comment]
Hi. No it is possible to CNAME to cloudflare I just need to manually check the dns records on cloudflare (as you can see in the screenshot). please proceed with setting the CNAME record so that I can do this.
Thank you

image

**Comment by DanyTPG** [comment]
@lakuapik

**Comment by lakuapik** [comment]
@DanyTPG please check from your side, i've added the cname.

image

**Comment by lakuapik** [comment]
@DanyTPG it works 🚀

image

thanks for the information!!

**Comment by lakuapik** [comment]
@DanyTPG could you resolve the conflict before i merge? thanks.

**Comment by DanyTPG** [comment]
@lakuapik done. thank you

**Pull request merged**
