### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by Rahuletto**

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@Rahuletto thedev.id team has created a CNAME for your site `rahuletto.thedev.id` 🎉

image

what you need to do next is to add `rahuletto.thedev.id` to your github page custom domain.

example: 

image

**Comment by Rahuletto** [comment]
The site's available. Thanks 😍

**Comment by lakuapik** [comment]
@Rahuletto great! i will merge this then.

**Comment by Rahuletto** [comment]
After this, I do get this chrome error
NET::ERR_CERT_COMMON_NAME_INVALID

>

**Comment by Rahuletto** [comment]
It's deployed bia GitHub pages

**Comment by Rahuletto** [comment]
In the GitHub pages

**Comment by lakuapik** [comment]
@Rahuletto can you try again?

i've checked the site and it still up and running, https.

image

**Comment by Rahuletto** [comment]
Yea it's fixed. Idk why it happened

**Pull request merged**
