### PR TITLE
izo

### PR DESCRIPTION
**Pull request by mrijoo**

### CODE REVIEW

**Comment by lakuapik** [comment]
@mrijoo can you please explain a bit why you add `thedev.id.mrijoo.com` instead of the root domain `mrijoo.com`? i've checked the site and its the same.

**Comment by mrijoo** [comment]
yes for now it is the same, why did I choose thedev.id.mrijoo.com? because in the future I will update it for my project.

**Comment by lakuapik** [comment]
@mrijoo which one will be updated for your next project? the `thedev.id.mrijoo.com` or the `mrijoo.com` ?

for site verification, we dont allow upcoming/maintenance-mode/alike website status, only active and live website is allowed.

**Comment by mrijoo** [comment]
thedev.id.mrijoo.com

**Comment by lakuapik** [comment]
@mrijoo, please make sure your next project is up first before requesting a subdomain.

i'am afraid i cannot proceed the `thedev.id.mrijoo.com` right now. 

@fransallen what do you think for this case?

**Comment by mrijoo** [comment]
for the next it will only change the appearance but the content remains the same.

**Comment by lakuapik** [comment]
@mrijoo got it, we'll wait what @fransallen says, if he allows it, i will create a cname for your site and proceed.

**Comment by mrijoo** [comment]
@lakuapik I have changed it

**Comment by lakuapik** [comment]
@mrijoo great!

a concern from me. could you change the subdomain from `thedev.id.mrijoo.com` to something like `zoo.mrijoo.com`? so it does not contain `thedev.id` in it. if thats ok, i will proceed. thanks.

**Comment by lakuapik** [comment]
screenshot for the new site:

image

**Comment by mrijoo** [comment]
I've replaced it.

**Comment by lakuapik** [comment]
@mrijoo thedev.id team already created a CNAME for your site `izo.thedev.id` 🎉

But unfornately, there is an SSL issue on your site.

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `izo.thedev.id`.

**Comment by mrijoo** [comment]
Done, thank you.

**Pull request merged**
