### PR TITLE
Added amaanwarsi

### PR DESCRIPTION
**Pull request by amaanwarsi**

### CODE REVIEW

**Comment by lakuapik** [comment]
@amaanwarsi please make sure your site is up and can be accessed so thedev.id team can verify it.

**Comment by amaanwarsi** [comment]
> @amaanwarsi please make sure your site is up and can be accessed so thedev.id team can verify it.
> 
> image

Check Now available

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@amaanwarsi thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `amaanwarsi.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by amaanwarsi** [comment]
> @amaanwarsi thedev.id team has created a CNAME for your site 🎉
> 
> but there is a ssl error issue, this is because of invalid custom domain configuration.
> 
> image
> 
> what you need to do next is add `amaanwarsi.thedev.id` to your github page custom domain. *dont forget to check enforce https.
> 
> example:
> 
> image

Site is now live at [amaanwarsi.thedev.id](https://amaanwarsi.thedev.id/)
Thank you for all the help!

**Comment by lakuapik** [comment]
@amaanwarsi great!

the site now accessible with thedev.id domain, i will merge this PR.

image

**Pull request merged**
