### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by JHubi1**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up and accessible, its a personal site:

image

**Comment by JHubi1** [comment]
Done!
But I still have one question:
Could I have a project (user.github.io/project) at project.thedev.id too?

**Comment by lakuapik** [comment]
@JHubi1 great now the site is accesable with thedev.id domain:

image

---

yes, you can do that. just like these:

https://github.com/thedev-id/thedev.id/blob/2b1a7d4109d6dda0f77b5b11cbdaea681abefb27/subdomains.json#L72-L76

**Comment by JHubi1** [comment]
Ok thanks!

**Comment by JHubi1** [comment]
Ok thanks!

**Pull request merged**
