### PR TITLE
Request domain arif for codewitharif-v3.vercel.app

### PR DESCRIPTION
**Pull request by NeuroNexul**

### CODE REVIEW

**Comment by NeuroNexul** [comment]
If all checks have passed, then why its not working ??

**Comment by lakuapik** [comment]
the site is up and accessible, its a personal portfolio website:

image

**Comment by lakuapik** [comment]
@NeuroNexul thedev.id team has created a cname for your site:

image

what you need to do next is configure `arif.thedev.id` in your vercel custom domain settings. and please remove your unecessary changes .gitpod file.

**Comment by NeuroNexul** [comment]
Thanks... The domain arif.thedev.id is now up and running...

**Comment by NeuroNexul** [comment]
@lakuapik I would like to inquire about the process of integrating Google AdSense into my website. During the enrollment process, I encountered a requirement to have a top-level domain, which subsequently led to my application being rejected.

image

**Comment by NeuroNexul** [comment]
> @lakuapik I would like to inquire about the process of integrating Google AdSense into my website. During the enrollment process, I encountered a requirement to have a top-level domain, which subsequently led to my application being rejected.
> 
> image

@lakuapik Please Reply...

**Pull request closed without merging**
