### PR TITLE
Please approve me - arwanfiles

### PR DESCRIPTION
**Pull request by arwanfiles**
Hi,
Ini sangat keren, mohon review PR saya dan kiranya bisa ditambahkan sebagai subdomain di thedev.id

Regards,
Arwafiles

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]

**Comment by lakuapik** [comment]
image

**Comment by lakuapik** [comment]
@arwanfiles thedev.id team already created a CNAME for your site. 

what you need to do next is to add `arwanfiles.thedev.id` to your github page custom subdomain.

go to https://github.com/arwanfiles/arwanfiles.github.io/settings/pages

example:

image

**Comment by arwanfiles** [comment]
Thanks for your approve, this site just live..

**Comment by lakuapik** [comment]
site is up with thedev.id domain

image

**Pull request merged**
