### PR TITLE
fix: adding dinvesting

### PR DESCRIPTION
**Pull request by FriendlyUser**

### CODE REVIEW

**Review by lakuapik — CHANGES_REQUESTED** [review]
@FriendlyUser hi there, i've just checked your site and looks like its a redirect to `http://stonks.dee.al`

do you still want thedev.id domain? if yes, for verification, can you explain a bit what the site is and why you need thedev.id domain?

**Comment by FriendlyUser** [comment]
I think you can close my request, I was just messing around with a variety of subdomains.

**Comment by FriendlyUser** [comment]
stonks.dee.al

is still redirected from dli-invest.github.io is there a reason I thought this pr wasnt merged in.

**Comment by lakuapik** [comment]
@FriendlyUser this is using github pages right? as far as i know github wont allow you to have multiple custom domain name. its either you use `stonks.dee.al` or `dinvesting.thedev.id`, if you prefer thedev you need to disable the stonks, or if you want both, setup a separate repository for each domain.

**Pull request closed without merging**
