### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by Cyteon**

### CODE REVIEW

**Comment by lakuapik** [comment]
@Cyteon i've visited your site, but unfornately the content did not meet our requirements:

- is a portfolio/personal/blog/project website
- not a hello-world/getting-started like website
- has enough content for verification

image

**Comment by Cyteon** [comment]
How much content is needed for verification?

**Comment by lakuapik** [comment]
@Cyteon it depends on the type of website. just as far as the content contain your profile, or enough blog/post or any kind of content.

**Comment by Cyteon** [comment]
Its a portfolio?

**Comment by Cyteon** [comment]
@lakuapik Its a portfolio?
Have added more, may you take a look, not finished with projects page and a little more work on homepage needed.

**Comment by lakuapik** [comment]
@Cyteon yup porfolio is a perfect fit!

feel free to re-open this PR or create new one whenever you feel ready.

**Pull request closed without merging**
