### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slorixsh**
I translated the README.md in my language.

### CODE REVIEW

**Comment by lakuapik** [comment]
@slorixsh thank you for your effor to translate thedev readme. but for now we do not plan to add multiple translation. may be for the next future we will. also, could you tell us what this is translated into?

**Comment by lakuapik** [comment]
ill mark this PR to next-phase.

**Comment by slorixsh** [comment]
@lakuapik I already did it so that the users who came to my profile would not say what does this do. I thought I'd let you know here.

**Comment by lakuapik** [comment]
@slorixsh we havent plan it so i will close this one for now. thanks.

**Pull request closed without merging**
