### PR TITLE
add la.thedev.id

### PR DESCRIPTION
**Pull request by lxjv**

### CODE REVIEW

**Comment by lakuapik** [comment]
@lxjv right now we dont allow 2 charater domain.

would you like `laker.thedev.id` or `lxjv.thedev.id`? thats still available.

**Comment by lxjv** [comment]
ah fair, ill take lxjv then

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@lxjv thedev.id team already created a CNAME for your site `lxjv.thedev.id` 🎉

But unfornately, there is a domain not found issue:

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `lxjv.thedev.id`.

**Comment by lxjv** [comment]
i just havent added that domain to my account yet, will fix now :D thank you

**Comment by lakuapik** [comment]
@lxjv one more thing before i merge, could you please update the subdomain file with the new one?

**Comment by lakuapik** [comment]
@lxjv thank you for the update, i've merged it!

**Comment by lxjv** [comment]
no problem and thank you!

**Pull request merged**
