### PR TITLE
add new domain ihsan

### PR DESCRIPTION
**Pull request by IhsanFikri**
Adding sub

### CODE REVIEW

**Comment by IhsanFikri** [comment]
adding ihsan.thedev.id

**Comment by lakuapik** [comment]
the site is up, can be acceseed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@IhsanFikri thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `ihsan.thedev.id` to your github page custom domain. *dont forget to check enforece https.

example:

image

**Comment by IhsanFikri** [comment]
image


Done

**Comment by lakuapik** [comment]
great! the site is now can be acessed with thedev.id domain.

image

@IhsanFikri for the console error, i think you need to configure your site again so it loads css/js from thedev.id domain instead of github.io.

**Comment by IhsanFikri** [comment]
image


done, Thank you.

**Pull request merged**
