### PR TITLE
Update subdomains.json

### PR DESCRIPTION
**Pull request by keshavashiya**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site is up, can be accessed, is a portfolio website:

image

**Comment by lakuapik** [comment]
@keshavashiya thedev.id team has created a CNAME for your site 🎉 

but there is a 404 not found issue, this is because of invalid custom domain configuration.

image

what you need to do next is add `keshavashiya.thedev.id` to your github page custom domain.

example:

image

**Comment by lakuapik** [comment]
@keshavashiya any update?

**Comment by keshavashiya-zluri** [comment]
@lakuapik sorry for late reply, yes I've updated Custom domain in GH pages. Thanks

**Comment by keshavashiya** [comment]
@lakuapik sorry for late reply, yes I've updated Custom domain in GH pages. Thanks

**Comment by lakuapik** [comment]
@keshavashiya please make sure you check the `Enforce HTTPS` also.

**Comment by keshavashiya-zluri** [comment]
@lakuapik Yes it's enabled.

**Comment by keshavashiya** [comment]
@lakuapik Yes it's enabled.

**Comment by lakuapik** [comment]
@keshavashiya great!

the site now can be accessed with thedev.id domain:

image

**Comment by keshavashiya** [comment]
@lakuapik Thanks, I can access it now.

**Pull request merged**
