### PR TITLE
Subdomain registration

### PR DESCRIPTION
**Pull request by dev0cloo**
Hello, creating a subdomain for my portfolio site. Thank you!

### CODE REVIEW

**Comment by lakuapik** [comment]
@dev0cloo please make sure your site is up and accessible for verification.

image

**Comment by dev0cloo** [comment]
@lakuapik hello, the [site](https://dev0cloo.github.io/portfolio/) is up and accessible now. Kindly verify, thank you.

**Comment by lakuapik** [comment]
the site is up and accessible, its a personal site:

image

**Comment by lakuapik** [comment]
@dev0cloo thedev.id team has created a CNAME for your site 🎉 

but there is a ssl error issue, this is because of invalid custom domain configuration.

what you need to do next is add `dev0cloo.thedev.id` to your github page custom domain. *dont forget to check enforce https.

example:

image

**Comment by dev0cloo** [comment]
@lakuapik thank you for verifying! I would like the custom domain to be `ocloo.thedev.id` and not `dev0cloo.thedev.id`. I have updated subdomains.json to reflect that. Kindly confirm if this is possible.

**Comment by lakuapik** [comment]
@dev0cloo i've changed it.

**Comment by dev0cloo** [comment]
@lakuapik Custom domain added and HTTPS Enforced. Thanks!

**Comment by lakuapik** [comment]
@dev0cloo great now your site is accessible with thedev.id domain:

image

**Pull request merged**
