### PR TITLE
added elvisvictor & scripthouse subdomains

### PR DESCRIPTION
**Pull request by elvis-ndubuisi**

### CODE REVIEW

**Comment by lakuapik** [comment]
the site `https://elvisndubuisi.vercel.app` is up, can be accessed, is a portfolio website.

image

the site `scripthouse.vercel.app` is up, can be accessed, is a portfolio website.

image

**Comment by lakuapik** [comment]
@elvis-ndubuisi thedev.id team already created a CNAME for your site 🎉

But unfornately, there is a not found issue on your site.

image

image

What you need to do next is make sure your site use HTTPS and make sure settings for custom domain is pointed to `elvisvictor.thedev.id` and `scripthouse.thedev.id`.

Please refer to [this vercel documentation](https://vercel.com/docs/concepts/projects/domains/add-a-domain).

**Comment by elvis-ndubuisi** [comment]
Thank you. I've added the domain to my vercel project.

**Comment by lakuapik** [comment]
@elvis-ndubuisi great!

the site is up and running using thedev.id domain 🚀

image

**Comment by lakuapik** [comment]
@elvis-ndubuisi but for the `scripthouse.thedev.id` looks like the content is changed? previously it was a blog right?

image

can you explain a bit about this one?

**Comment by elvis-ndubuisi** [comment]
Yes. The scripthouse is currently on pause since its backend was in heroku.
So, I decided to temporarily add the domain name to the Baabar project

**Comment by lakuapik** [comment]
@elvis-ndubuisi for that case, i will remove the CNAME for the `scripthouse` because its not the same as we've verified.

Feel free to open new PR for your next project.

**Comment by lakuapik** [comment]
@elvis-ndubuisi i will merge only `elvisvictor.thedev.id`

**Pull request merged**
