### PR TITLE
Add darcoz at subdomains.json

### PR DESCRIPTION
**Pull request by DarcoZav**

### CODE REVIEW

**Review by lakuapik — APPROVED** [review]
the site is up, can be accessed, a portfolio website.

image

**Comment by lakuapik** [comment]
@DarcoZav thedev.id team already created a CNAME for your site 🎉

what you need to do next is to add `darcoz.thedev.id` to your github page custom subdomain.

go to https://github.com/DarcoZav/darcozab.github.io/settings/pages

example: 

image

**Comment by DarcoZav** [comment]
Bro i think you put the wrong repo because mine is darcozav not darcozab

**Comment by lakuapik** [comment]
@DarcoZav haha, you know what to do. set it up on your repo.

**Comment by DarcoZav** [comment]
Thank you very much it work 😎

**Pull request merged**
