### PR TITLE
add portfolio site

### PR DESCRIPTION
**Pull request by hunghg255**

### CODE REVIEW

**Comment by lakuapik** [comment]
@hunghg255 you're not allowed to request multiple domain at the same time, just request one domain per PR.

**Comment by lakuapik** [comment]
sort the domain alphabetically, just like the others.

**Comment by hunghg255** [comment]
@lakuapik I got it, I updated my commit, thanks you

**Comment by lakuapik** [comment]
@hunghg255 can you explain a bit about your project and why it needs thedev.id domain?



image

**Comment by hunghg255** [comment]
@lakuapik @lakuapik I just want to use another domain other than vercel, it's ok, right?

**Comment by lakuapik** [comment]
that not enough, your project is a url shortener, which can generate new url. to prevent abuse, we do not allow that kind of project. 

your site must be in one of these criteria:
- a personal site
- a portfolio website
- a blog website
- a project (documentation) website

and has enough content for verification.

**Comment by hunghg255** [comment]
@lakuapik ah, ok, I updated to my portfolio site, can you help me recheck?

**Comment by lakuapik** [comment]
sure, your site is eligible. its accessible and its a portfolio website 

image

**Comment by lakuapik** [comment]
@hunghg255 thedev.id team has created a cname for your site `hung.thedev.id`

image

what you need to do next is configure your vercel domain to use thedev.id domain, and make sure enable https.

**Comment by hunghg255** [comment]
@lakuapik thank you so much, it works now

**Pull request merged**
